// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../client.dart';
import '../database.dart';
import '../protocol/signer.dart';
import 'options.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<_ClientBuilder>>
abstract class ClientBuilder implements RustOpaqueInterface {
  /// Build client
  Client build();

  /// Set database
  ClientBuilder database({required NostrDatabase database});

  /// New client builder
  factory ClientBuilder() =>
      NostrSdk.instance.api.crateApiClientBuilderClientBuilderNew();

  /// Set opts
  ClientBuilder opts({required ClientOptions opts});

  /// Set signer
  ClientBuilder signer({required NostrSigner signer});
}
