// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../protocol/event.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'notification.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

@freezed
sealed class RelayPoolNotification with _$RelayPoolNotification {
  const RelayPoolNotification._();

  /// Received an [`Event`]. Does not include events sent by this client.
  const factory RelayPoolNotification.event({
    /// Relay url
    required String relayUrl,

    /// Subscription ID
    required String subscriptionId,

    /// Event
    required Event event,
  }) = RelayPoolNotification_Event;

  /// Received a [`RelayMessage`]. Includes messages wrapping events that were sent by this client.
  const factory RelayPoolNotification.message({
    /// Relay url
    required String relayUrl,

    /// Relay Message
    required String message,
  }) = RelayPoolNotification_Message;

  /// Shutdown
  ///
  /// This notification variant is sent after [`Client::shutdown`] method is called and all connections have been closed.
  const factory RelayPoolNotification.shutdown() =
      RelayPoolNotification_Shutdown;
}
