// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `_ConnectionTarget`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `from`, `from`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `addr`, `autoconnect`, `automatic_authentication`, `connection`, `embedded_tor_with_path`, `embedded_tor`, `gossip`, `min_pow`, `mode`, `target`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<_ClientOptions>>
abstract class ClientOptions implements RustOpaqueInterface {
  factory ClientOptions() =>
      NostrSdk.instance.api.crateApiClientOptionsClientOptionsNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<_Connection>>
abstract class Connection implements RustOpaqueInterface {
  factory Connection() =>
      NostrSdk.instance.api.crateApiClientOptionsConnectionNew();
}
