// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Output
class SendEventOutput {
  /// Event ID
  final String id;

  /// Set of relays that success
  final Set<String> success;

  /// Map of relays that failed, with related errors.
  final Map<String, String> failed;

  const SendEventOutput({
    required this.id,
    required this.success,
    required this.failed,
  });

  @override
  int get hashCode => id.hashCode ^ success.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendEventOutput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          success == other.success &&
          failed == other.failed;
}
