// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'options.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `try_from`

@freezed
sealed class ConnectionMode with _$ConnectionMode {
  const ConnectionMode._();

  /// Direct connection
  const factory ConnectionMode.direct() = ConnectionMode_Direct;

  /// Connect through proxy
  ///
  /// This doesn't work on web!
  const factory ConnectionMode.proxy({
    /// Socket addr (i.e. 127.0.0.1:9050)
    required String addr,
  }) = ConnectionMode_Proxy;

  /// Connect through tor network
  ///
  /// This doesn't work on web!
  const factory ConnectionMode.tor({
    /// Path where to store data
    ///
    /// This is required for `android` and `ios` targets!
    String? customPath,
  }) = ConnectionMode_Tor;
}
