// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../event.dart';
import '../event/unsigned.dart';
import '../key/public_key.dart';
import '../signer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<_UnwrappedGift>>
abstract class UnwrappedGift implements RustOpaqueInterface {
  /// Unwrap Gift Wrap event
  ///
  /// Internally verify the `seal` event
  static Future<UnwrappedGift> fromGiftWrap(
          {required NostrSigner signer, required Event giftWrap}) =>
      NostrSdk.instance.api.crateApiProtocolNipsNip59UnwrappedGiftFromGiftWrap(
          signer: signer, giftWrap: giftWrap);

  /// Get rumor
  UnsignedEvent rumor();

  /// Get sender public key
  PublicKey sender();
}
